# Generated by Django 4.2.2 on 2023-08-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0002_empleado_en_servicio_historialempleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialempleado',
            name='fecha_cambio',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
