# Generated by Django 4.2.2 on 2023-08-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0003_historialempleado_fecha_cambio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialempleado',
            name='act_en_servicio',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='historialempleado',
            name='ant_en_servicio',
            field=models.BooleanField(),
        ),
    ]
