# Generated by Django 4.2.2 on 2023-08-07 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0004_alter_historialempleado_act_en_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialempleado',
            name='id_empleado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Administracion.empleado'),
            preserve_default=False,
        ),
    ]
