# Generated by Django 4.2.2 on 2023-08-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0006_empleado_cedula_datostemporalesnomina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datostemporalesnomina',
            name='hrs_normales_trabajadas',
            field=models.IntegerField(default=40),
        ),
    ]
