# Generated by Django 4.2.2 on 2023-08-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0008_rename_hrs_diurnas_trabajadas_datostemporalesnomina_hrs_dominical_nocturnas_trabajadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datostemporalesnomina',
            name='pago_mes',
            field=models.FloatField(default=0),
        ),
    ]
