# Generated by Django 4.2.2 on 2023-08-12 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Administracion', '0009_alter_datostemporalesnomina_pago_mes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstanciaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('cargo', models.CharField(max_length=100)),
                ('pago', models.FloatField()),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administracion.empleado')),
            ],
        ),
    ]
